services:
  discord-bot-client:
    build:
      context: ./DiscordBot
      dockerfile: Dockerfile
    tty: true
    stdin_open: true

  discord-bot-webui:
    build:
      context: ./DiscordBotWebUI
      dockerfile: Dockerfile
    ports:
      - '4444:8080'


networks: 
  custom_bridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.100.0/24"
          gateway: "172.20.100.1"